# 企业微信群机器人
[provider.workweixin_bot]
# webhook 地址
endpoint.url = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxx"
# 每分钟最高速率=18次，最多20次
rate_limit.minute.burst = 18



# 飞书自定义机器人
[provider.feishu_bot]
# webhook 地址
endpoint.url = "https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxx"
# 签名密钥
secret = "xxx"
# 每分钟最高速率=98次，最多100次
rate_limit.minute.burst = 98
# 每秒4次，最多5次
rate_limit.rate.frequency = 4



# 钉钉自定义机器人
[provider.dingtalk_bot]
# webhook 地址
endpoint.url = "https://oapi.dingtalk.com/robot/send?access_token=xxxxxx"
# 签名密钥
secret = "xxx"



# Slack机器人
[provider.slack_bot]
# webhook 地址
endpoint.url = "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX"
# 通道代理：没有配置代理使用全局代理；配置了代理，通道使用自己的代理；配置不使用代理 proxy="no"。
#proxy = "http://127.0.0.1:1080"



# Webhook 文档: provider_webhook.md
[provider.webhook]
# webhook 地址
endpoint.url = "http://localhost/xxxxxx"
# webhook http method，可选用一个: GET、POST、PUT、PATCH、DELETE，默认=POST
endpoint.method = "POST"
# 可选用一个: json、form，默认=json
content_type = "json"



# 发送消息
[delivery]
# 全局代理：所有通道使用这个代理，除非通道自己配置了代理；
# 代理url格式：
#   socks5://username:password@proxy_server_ip:port
#   socks5://username:password@proxy_server_domain:port
#   http://username:password@proxy_server_ip:port
#   https://username:password@proxy_server_domain:port
#proxy = "http://127.0.0.1:1080"

# 失败重试
[delivery.retry]
# 重试次数 0=不重试
count = 5
# 间隔时间，单位秒，最大900秒=15分钟
interval = 10



# api 端口配置
[api]
# host="localhost"，只能在本机访问；host=""，可以对外服务。
host = "localhost"
# 默认值
port = 39270



# 日志配置
[log]
# 屏幕显示
console = true
# 保存到文件，日志文件在 log 目录
file = true
# 日志级别: debug, info, warn, error
level = "info"