# 企业微信群机器人
[provider.workweixin_bot]
# webhook 地址
endpoint.url = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxx"
# 每分钟最高速率=18次，最多20次
rate_limit.minute.burst = 18



# 飞书自定义机器人
[provider.feishu_bot]
# webhook 地址
endpoint.url = "https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxx"
# 签名密钥
secret = "xxx"
# 每分钟最高速率=98次，最多100次
rate_limit.minute.burst = 98
# 每秒4次，最多5次
rate_limit.rate.frequency = 4



# 钉钉自定义机器人
[provider.dingtalk_bot]
# webhook 地址
endpoint.url = "https://oapi.dingtalk.com/robot/send?access_token=xxxxxx"
# 签名密钥
secret = "xxx"



# Slack机器人
[provider.slack_bot]
# webhook 地址
endpoint.url = "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX"



# 失败重试
[delivery.retry]
# 重试次数 0=不重试
count = 5
# 间隔时间，单位秒，最大900秒=15分钟
interval = 10



# api 端口配置
[api]
# 默认值
port = 39270



# 日志配置
[log]
# 屏幕显示
console = true
# 保存到文件，日志文件在 log 目录
file = true
# 日志级别: debug, info, warn, error
level = "info"