# 企业微信群机器人
[provider.workweixin_bot]
# webhook 地址
endpoint.url = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxx"
# 每分钟最高速率=18次，最多20次
rate_limit.minute.burst = 18



# 飞书自定义机器人
[provider.feishu_bot]
# webhook 地址
endpoint.url = "https://open.feishu.cn/open-apis/bot/v2/hook/xxx"
# 签名密钥
secret = "xxx"
# 每分钟最高速率=90次，最多100次
rate_limit.minute.burst = 90



# 钉钉自定义机器人
[provider.dingtalk_bot]
# webhook 地址
endpoint.url = "https://oapi.dingtalk.com/robot/send?access_token=xxx"
# 签名密钥
secret = "xxx"
# 每分钟最高速率=18次，最多20次
rate_limit.minute.burst = 18



# 失败重试
[delivery.retry]
# 重试次数 0=不重试
count = 0
# 间隔时间，单位秒，最大900秒=15分钟
interval = 10



# api 端口配置
[api]
# 默认值
port = 39270